### ISSUE TITLE
the difference of cli

### ISSUE THREAD

**Issue by gjj0430** [RealVNF/DeepCoord#4]
**Dear author, I download and install requirements according to the README, but my cli is like this**
Options:
  --seed INTEGER            Specify the random seed for the environment and
                            the learning agent.
  -t, --test TEXT           Name of the training run whose weights should be
                            used for testing.
  -w, --weights TEXT        Continue training with the specified weights
                            (similar to testing)
  -a, --append-test         Append a test run of the previously trained agent.
  -v, --verbose             Set console logger level to debug. (Default is
                            INFO)
  -b, --best                Test the best of the trained agents so far.
  -ss, --sim-seed INTEGER   Set the simulator seed
  -gs, --gen-scenario PATH  Diff. sim config file for additional scenario test
  -h, --help 

**which is different to** 

Options:
  --seed INTEGER               Specify the random seed for the environment and
                               the learning agent.
  -t, --test TEXT              Name of the training run whose weights should
                               be used for testing.
  -w, --weights TEXT           Continue training with the specified weights
                               (similar to testing)
  -a, --append-test            Append a test run of the previously trained
                               agent.
  -v, --verbose                Set console logger level to debug. (Default is
                               INFO)
  -b, --best                   Test the best of the trained agents so far.
  -e, --test-episodes INTEGER  Set the number of testing episodes
  -ss, --sim-seed INTEGER      Set the simulator seed
  -gs, --gen-scenario PATH     Diff. sim config file for additional scenario
                               test
  -h, --help                   Show this message and exit.

**I am confused, is it my fault like download different version of the code?**

**looking forward to your reply.**

**Comment by stefanbschneider** [comment]
Hi @gjj0430 , good catch. You mean that the `-e` from the readme is missing? Or do you refer to something else?

You have the correct version installed, just the readme is outdated a bit. The `-e` option was removed in the v1.1 release. I'll update the readme.

**Comment by gjj0430** [comment]
Thanks for your timely answer, the problem has been solved. I'm an undergraduate facing graduation thesis, and my work is to reproduce this paper. Maybe I will get in trouble again during my work, so I will be very grateful if you could spare time to answer my question. @stefanbschneider

**Comment by stefanbschneider** [comment]
I'm happy to hear DeepCoord is being picked up by others!

Good luck with your theses. I'll try to help if you have questions - but can't make any promises of course.
